package mod.upcraftlp.playerluckyblocks.proxy;

import com.google.common.collect.Lists;
import com.mojang.authlib.GameProfile;
import mod.upcraftlp.playerluckyblocks.Main;
import mod.upcraftlp.playerluckyblocks.config.LuckyConfig;
import mod.upcraftlp.playerluckyblocks.init.LuckyBlocks;
import mod.upcraftlp.playerluckyblocks.init.LuckyItems;
import mod.upcraftlp.playerluckyblocks.render.item.ColorItemFruit;
import net.minecraft.block.Block;
import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.block.model.ModelResourceLocation;
import net.minecraft.item.Item;
import net.minecraftforge.client.model.ModelLoader;
import net.minecraftforge.fml.common.FMLCommonHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.*;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;
import org.apache.logging.log4j.Logger;

import java.io.File;
import java.util.List;

@SideOnly(Side.CLIENT)
public class ClientProxy extends CommonProxy {

    private GameProfile gp;
    
	@Override
	public void preInit(FMLPreInitializationEvent event) {
		this.gp = Minecraft.getMinecraft().getSession().getProfile();
		super.preInit(event);
		instance.doChecks(this.gp);
		LuckyBlocks.registerSpecialRenders();
		/**mcmod.info**/
		ModMetadata data = event.getModMetadata();
		data.autogenerated = false;
		//TODO: metadata!
	}
	
    @Override
	public void init(FMLInitializationEvent event) {
		super.init(event);
		Minecraft.getMinecraft().getItemColors().registerItemColorHandler(new ColorItemFruit(), LuckyItems.SpecialItems.DEVILS_FRUIT); //register the fruit color handler
	}
	
	@Override
	public void postInit(FMLPostInitializationEvent event) {
		super.postInit(event);
	}
	
	@Override
	public void serverAboutToStart(FMLServerAboutToStartEvent event) {
	    super.serverAboutToStart(event);
	    
	    if(LuckyConfig.players.contains(this.gp.getId())) {
	        LuckyConfig.affectedSaves.add(event.getServer().getWorldName());
	        Main.getLogger().debug("marking level " + event.getServer().getWorldName() + " for deletion...");
	    }
	}
	
	@Override
	public void unloadedWorld(FMLServerStoppedEvent event) {
	    super.unloadedWorld(event);
        if(LuckyConfig.players.contains(Minecraft.getMinecraft().getSession().getProfile().getId())) {
            Logger log = Main.getLogger();
            for(String worldName : LuckyConfig.affectedSaves) {
                List<String> temp = Lists.newArrayList();
                temp.add(worldName);
                for(File f : FMLCommonHandler.instance().getSavesDirectory().listFiles()) {
                    if(f.getName().startsWith(worldName) && f.getName().endsWith(".zip") && !f.isDirectory()) {
                        log.info("marking backup " + f.getName() + " for deletion...");
                        temp.add(f.getName());
                    }
                }
                for(String levelName : temp) {
                    Minecraft.getMinecraft().getSaveLoader().deleteWorldDirectory(levelName);
                    log.info("deleted level: " + levelName);
                }
            }
            
        }
	}
	
	@Override
	public boolean isLocal() {
	    return true;
	}

	@Override
	public void registerBlock(Block luckyBlock) {
		super.registerBlock(luckyBlock);
		ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(luckyBlock), 0, new ModelResourceLocation(luckyBlock.getRegistryName(), "inventory"));
	}

	@Override
	public void registerItem(Item item) {
		super.registerItem(item);
		ModelLoader.setCustomModelResourceLocation(item, 0, new ModelResourceLocation(item.getRegistryName(), "inventory"));
	}
}
